c90:
	gcc demo1.c -Wall -Wextra -Werror -std=c90 -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition

c99:
	gcc demo1.c -Wall -Wextra -Werror -std=c99 -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition
