c90:
	gcc demo0.c -Wall -Wextra -std=c90 -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition

c99:
	gcc demo0.c -Wall -Wextra -std=c99 -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition
