c90:
	gcc demo7.c -Wall -Wextra -Werror -std=c90 -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition

c99:
	gcc demo7.c -Wall -Wextra -Werror -std=c99 -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition

c11:
	gcc demo7.c -Wall -Wextra -Werror -std=c11 -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wold-style-definition
